import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./_layout-resources/Nav";
import ToastProvider from "@/shared/components/Toast/ToastCTX";
import PopUpProvider from "@/shared/components/PopUp/PopUpCTX";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app" };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* <head>
        <script crossOrigin="anonymous" src="//unpkg.com/react-scan/dist/auto.global.js" />
      </head> */}
      <body className={`${geistSans.variable} ${geistMono.variable} bg-[#FAFAFA] antialiased`}>
        <ToastProvider>
          <PopUpProvider>
            <Nav />
            {children}
          </PopUpProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
